// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"go-auth-otp-service/src/api/http/controllers"
	"go-auth-otp-service/src/api/http/controllers/authentication"
	"go-auth-otp-service/src/api/http/middlewares"
	"go-auth-otp-service/src/database"
)

// Injectors from wire.go:

func GetAuthenticationContainer() *AuthenticationContainer {
	databaseDatabase := database.GetInstance()
	userRepository := ProvideUserRepository(databaseDatabase)
	userService := ProvideUserService(userRepository)
	otpService := ProvideOTPService()
	jwtService := ProvideJwtService()
	accessTokenRepository := ProvideAccessTokenRepository(databaseDatabase)
	accessTokenService := ProvideAccessTokenService(accessTokenRepository, jwtService, userRepository)
	registerService := ProvideRegisterService(userService, otpService, jwtService, accessTokenService)
	registerController := ProvideUserRegisterController(registerService)
	authenticationMiddleware := ProvideAuthenticationMiddleware(accessTokenService)
	accessTokenController := ProvideUserAccessTokenController(accessTokenService)
	authenticationContainer := &AuthenticationContainer{
		UserRegisterController:   registerController,
		AuthenticationMiddleware: authenticationMiddleware,
		AccessTokenController:    accessTokenController,
	}
	return authenticationContainer
}

func GetUserContainer() *UserContainer {
	databaseDatabase := database.GetInstance()
	userRepository := ProvideUserRepository(databaseDatabase)
	userService := ProvideUserService(userRepository)
	userController := ProvideUserController(userService)
	userContainer := &UserContainer{
		UserController: userController,
	}
	return userContainer
}

// wire.go:

type (
	AuthenticationContainer struct {
		UserRegisterController   *authentication.RegisterController
		AuthenticationMiddleware *middlewares.AuthenticationMiddleware
		AccessTokenController    *authentication.AccessTokenController
	}
	UserContainer struct {
		UserController *controllers.UserController
	}
)
