// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"go-auth-otp-service/src/api/http/controllers/authentication"
	"go-auth-otp-service/src/database"
)

// Injectors from wire.go:

func GetAuthenticationContainer() *AuthenticationContainer {
	databaseDatabase := database.GetInstance()
	userRepository := ProvideUserRepository(databaseDatabase)
	userService := ProvideUserService(userRepository)
	otpService := ProvideOTPService()
	registerService := ProvideRegisterService(userService, otpService)
	registerController := ProvideUserRegisterController(registerService)
	authenticationContainer := &AuthenticationContainer{
		UserRegisterController: registerController,
	}
	return authenticationContainer
}

// wire.go:

type (
	AuthenticationContainer struct {
		UserRegisterController *authentication.RegisterController
	}
)
